# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MPSwiftLintAdapter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MPSwiftLintAdapter
  pod 'mParticle-Apple-SDK', '~> 7.0'

  target 'MPSwiftLintAdapterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MPSwiftLintAdapterUITests' do
    # Pods for testing
  end

end
