name: Build
on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: cd mpswiftlint
    - run: swift build
    - run: cd ../MPSwiftLintAdapter
    - run: pod install
    - run: xcodebuild -workspace MPSwiftLintAdapter.xcworkspace -scheme MPSwiftLintAdapter CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    